### ISSUE TITLE
[Bug]: Can't build on xcdoe 16.0

### ISSUE THREAD

**Issue by MohamedAlsadek** [apivideo/api.video-swift-client#95]
### Version

1.3.4

### Environment that reproduces the issue

After updating to the latest SDK and xcode16.0 I am having the following error

Call can throw but is not marked with 'try'

in this line 
https://github.com/apivideo/api.video-swift-client/blob/main/Sources/AlamofireImplementations.swift#L416

now I can't build my project anymore, can you please help ? 

### Is it reproducible in the example application?

Not tested

### Reproduction steps

just update and try to build

### Expected result

app builds

### Actual result

Call can throw but is not marked with 'try'

in this line 
https://github.com/apivideo/api.video-swift-client/blob/main/Sources/AlamofireImplementations.swift#L416

**Comment by MohamedAlsadek** [comment]
the issue is related to updating AlamoFire to latest, when I checked your example you are using alamo fire 5.4.4 and when I downgraded my Alamofire, now it works 

can you please fix this problem so we are free to update

**Comment by ThibaultBee** [comment]
Fixed in [v1.3.5](https://github.com/apivideo/api.video-swift-client/releases/tag/v1.3.5)
